name: Daily dots

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering
  pull_request:

jobs:
  calculate-uuid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Calculate the uuid of the day
        id: uuid
        run: |
          FILE="uuid"
          dailyuuid=$(uuidgen)
          echo $dailyuuid >> $FILE
          echo "uuid=$dailyuuid" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: "uuid-of-the-day/${{ steps.uuid.outputs.uuid }}"
          title: "UUID of the day"
          body: "I spent some time calculating this UUID this morning"
          commit-message: "uuid of the day: ${{ steps.uuid.outputs.uuid }}"
          committer: "zetta <204105+zetta@users.noreply.github.com>"
          author: "zetta <204105+zetta@users.noreply.github.com>"
          base: main

      - name: Auto-Merge PR
        if: steps.cpr.outputs.pull-request-number
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --merge --repo $GITHUB_REPOSITORY --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
